services:
  ansible:
    image: ghcr.io/ansible-community/community-ee-base:2.19.5-1
    container_name: liberte-ansible
    working_dir: /work
    stdin_open: true
    tty: true
    volumes:
      - .:/work
    env_file:
      - .env
    environment:
      ANSIBLE_CONFIG: /work/ansible.cfg
