---
ansible_host: "{{ lookup('env', 'INFRA_SSH_HOST') }}"
ansible_user: "{{ lookup('env', 'INFRA_SSH_USER') | default('root', true) }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'INFRA_SSH_PRIVATE_KEY_FILE') | default(omit, true) }}"
ansible_python_interpreter: "/usr/bin/python3"
